### ISSUE TITLE
Make __init__.py pythonic again! [MIPA]

### ISSUE THREAD

**Issue by itsnamgyu** [hubaimaster/aws-interface#1]
According to [this post](http://mikegrouchy.com/blog/2012/05/be-pythonic-__init__py.html), \_\_init\_\_.py should only import classes, functions etc. from submodules within the package. Such classes and functions should not be declared within \_\_init\_\_.py itself. Rather, they should be in a separate .py file within the package.

**Comment by hubaimaster** [comment]
Please note that we have finished editing

**Comment by hubaimaster** [comment]
Thanks!
