### ISSUE TITLE
lambda code 에서 app_id.txt , recipe.json I/O 하는 부분에서 실행 시간 측정해봐야할듯

### ISSUE THREAD

**Issue by hubaimaster** [hubaimaster/aws-interface#15]
느낌상 그 부분에서 시간을 쓸데없이 낭비할거 같아서 측정해보고 낭비한다면,
Cloud API 생성시 해당 파일 내용을 디렉토리에 빼지 않고, 파일에 내장 시키는게 좋을 것 같음.

**Comment by itsnamgyu** [comment]
Django Debugger 한번 톺아보십셔~ 
https://www.youtube.com/watch?v=zFuaU3Sl4-c

**Comment by hubaimaster** [comment]
앗 참고하겠습니다 👍 근데 저 코드는 aws lambda 에 올려서 실행하는거라 장고 프레임워크 위에서 동작하는 코드는 아닙니다!

**Comment by itsnamgyu** [comment]
아하링..
