### ISSUE TITLE
is shutil necessary?

### ISSUE THREAD

**Issue by juice500ml** [hubaimaster/aws-interface#16]
https://github.com/hubaimaster/aws-interface/blob/master/requirements.txt#L4
[shutil @ python std lib](https://docs.python.org/3/library/shutil.html)

**Comment by hubaimaster** [comment]
아 파이썬 기본 라이브러리였군요~ 감사합니다!

**Comment by hubaimaster** [comment]
덕분에 수정했습니다 :)
