### ISSUE TITLE
Generate SDK에서 zip파일을 거치지 않고 메모리 상에서 binary 추출하면 좋을듯

### ISSUE THREAD

**Issue by itsnamgyu** [hubaimaster/aws-interface#23]

**Comment by hubaimaster** [comment]
shutil.make_archive 메소드가 out_dir 을 파라메터로 받아서 거기에 파일을 만들어주기때문에 일단 이 방법을 채용함! 근데 나중에 다른 방법 찾으면 인메모리로 바꾸는게 좋을듯!
